name: Build and Release

on:
  push:
    branches: ["master"]
    tags:
      - "v*"
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  OUTDIR: ${{ github.workspace }}/dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
            submodules: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Run the Cake script
      uses: cake-build/cake-action@v1
      with:
          verbosity: Diagnostic

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PipGUI V2.exe
        path: ${{ env.OUTDIR }}/PipGUI V2.exe

    - name: "Build & test"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ${{ env.OUTDIR }}\PipGUI V2.exe
